### ISSUE TITLE
Form inputs in the cart view are read-only

### ISSUE THREAD

**Issue by chlowell** [Glimpse/StickerApp#56]
In the prior app, users would enter their name and email address in the cart view before checking out. Now we've added authentication, unauthenticated users cannot check out, these fields are populated from user profiles, and they are read-only.

Should we render the fields only for authenticated users, and perhaps make them writable?

**Comment by mjrousos** [comment]
As an update, the design we landed on here was to not show the form to anonymous users and to update it to be writeable for authenticated users.

**Comment by mjrousos** [comment]
Curiously, the form appears to be writeable. Perhaps someone already fixed that half of this? I'll just hide it for anonymous users.

**Comment by mjrousos** [comment]
Seems the forms isn't 'read-only' per se, it's just not hooked up to reflect input through the React plumbing. I'll address that.
